service: mailer

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: us-east-1
  environment:
    ZEPTO_MAIL_API_KEY_NAME: ${env:ZEPTO_MAIL_API_KEY_NAME, ''}
    ZEPTO_MAIL_API_KEY: ${env:ZEPTO_MAIL_API_KEY, ''}
    HARDCODED_WEBSITES_FILE_PATH: ${env:HARDCODED_WEBSITES_FILE_PATH, ''}
    AUTHORIZED_WEBSITES_S3_BUCKET_NAME: ${env:AUTHORIZED_WEBSITES_S3_BUCKET_NAME, ''}
    RECAPTCHA_TEST_SITE_KEY: ${env:RECAPTCHA_TEST_SITE_KEY, ''}
    ENV: ${env:ENV, ''}

functions:
  api:
    handler: src/api/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
