name: Deploy

on:
  push:
    branches: [main]

env:
  ZEPTO_MAIL_API_KEY_NAME: ${{ vars.ZEPTO_MAIL_API_KEY_NAME }}
  ZEPTO_MAIL_API_KEY: ${{ secrets.ZEPTO_MAIL_API_KEY }}
  AUTHORIZED_WEBSITES_S3_BUCKET_NAME: "mailer-authorized-websites"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Deploy
        run: npm run deploy
